### ISSUE TITLE
Clash of licenses

### ISSUE THREAD

**Issue by tursics** [dbbahnhoflive/dbbahnhoflive-ios#1]
This project is Open Source and use an open Apache license. But some/many files are sublicensed (?) with a strong non-open copyright by Scholz and Volkmer.

E.g. dbbahnhoflive-ios/public/OpenSourceAPI/MBNewsRequestManager.m

//
//  MBNewsRequestManager.m
//  MeinBahnhof
//
//  Created by Heiko on 19.11.19.
//  Copyright © 2019 ScholzVolkmer. All rights reserved.
//

Please change ALL files to respect the Apache license. An Open Source project should be open.

Thomas

**Comment by cornelius** [comment]
One good way to do that would be to follow the conventions outlined by the [REUSE project](https://reuse.software): https://reuse.software/faq/#step-2. That would mean adding information in the headers which looks like this:

```
// SPDX-FileCopyrightText: [year] [copyright holder] <[email address]>
//
// SPDX-License-Identifier: Apache-2.0
```

**Comment by SuVpmoran** [comment]
Hi @tursics, hi @cornelius ,
thank you for bringing this topic to the surface. We will take care of it and work on a more transparent and clear way to communicate the license handling in this project.

**Comment by HMinning** [comment]
replaced license information in the source files
