### ISSUE TITLE
Unable to build master

### ISSUE THREAD

**Issue by basti481** [dbbahnhoflive/dbbahnhoflive-ios#1]
**Describe the bug**
Using current master i am unable to build the project (without modifications).

```
public/MeinBahnhofOpenSource/StationSearch/MBStationSearchViewController.m:26:9: 'MBTrackingConsentViewController.h' file not found
```

A build was possible after removing all reference of `MBTrackingConsentViewController` from that file.

**To Reproduce**
1. Check out master
2. open the project in xcode
3. run a build

**Expected behavior**
You should be able to do a clean checkout from master and finish a successful build without any errors

**Comment by HMinning** [comment]
Thank you for opening this issue and sorry about that error. The repo is now updated with the latest code and it builds fine.
